name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    tags:
      - v*
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=500s
      - name: Test
        run: make test
